server:
  port: 8080
spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      routes:
        - id: msusers
          uri: lb://msusers
          predicates:
            - Path=/api/v1/users
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_URL:localhost:8761/eureka/}
